import imageIndex from '../assets/imageIndex';

export const chatList = [
  // {
  //   id: 1,
  //   name: 'Paula Weber',
  //   image: imageIndex.userImage,
  //   lastMessage: 'Conveying or northward offending...',
  //   by: '',
  //   when: '3 min',
  //   read: false,
  // },
  // {
  //   id: 2,
  //   name: 'Dorothy Mccoy',
  //   image: imageIndex.userImage,
  //   lastMessage: 'Lose away off why half led have near...',
  //   by: '',
  //   when: '1 min',
  //   read: true,
  // },
  // {
  //   id: 3,
  //   name: 'Jeanette Fernandez',
  //   image: imageIndex.userImage,
  //   lastMessage: ' Okay, have a nice day :)',
  //   by: 'You',
  //   when: '2 hours',
  //   read: true,
  //   online: true,
  // },
  // {
  //   id: 4,
  //   name: 'Tony Chavez',
  //   image: imageIndex.userImage,
  //   lastMessage: 'Tell us about excursions to the sea...',
  //   by: '',
  //   when: '8 hours',
  //   read: true,
  // },
  // {
  //   id: 5,
  //   name: 'Howard Copeland',
  //   image: imageIndex.userImage,
  //   lastMessage: 'Mountain hikes are exciting...',
  //   by: 'You',
  //   when: 'Yesterday',
  //   read: true,
  // },
  // {
  //   id: 6,
  //   name: 'Catherine Patton',
  //   image: imageIndex.userImage,
  //   lastMessage: 'Okay, waiting for an invitation :)',
  //   by: '',
  //   when: '2 days',
  //   read: true,
  // },
  // {
  //   id: 7,
  //   name: 'Tom Bradley',
  //   image: imageIndex.userImage,
  //   lastMessage: 'In as of whole as match asked.',
  //   by: '',
  //   when: '5 days',
  //   read: true,
  // },
  // {
  //   id: 8,
  //   name: 'Victoria Erickson',
  //   image: imageIndex.userImage,
  //   lastMessage: 'We had a great time together...',
  //   by: 'You',
  //   when: '1 week',
  //   read: true,
  // },
  // {
  //   id: 9,
  //   name: 'Felix Drake',
  //   image: imageIndex.userImage,
  //   lastMessage: 'This NFT collection is the best in the...',
  //   by: '',
  //   when: '2 week',
  //   read: true,
  // },
  // {
  //   id: 10,
  //   name: 'Annette Mullins',
  //   image: imageIndex.userImage,
  //   lastMessage: 'I got these percentages after...',
  //   by: 'You',
  //   when: '1 month',
  //   read: true,
  // },
  // {
  //   id: 11,
  //   name: 'Ronnie Swanson',
  //   image: imageIndex.userImage,
  //   lastMessage: 'You can join my shared co-batching...',
  //   by: '',
  //   when: '3 month',
  //   read: true,
  // },
];
